function CT_Processing
    figObject = createMainFigure();
    %Create Menus
    menuObjects = createMenuObjects(figObject);
end

function figObject = createMainFigure()
    %Get the screen size
    screenSize = get(0, 'ScreenSize');
    figObject = figure('Tag', 'mainFig',...
        'MenuBar', 'None',...
        'NumberTitle', 'Off',...
        'Name', 'New CT Processing V 0.0.1dev',...
        'Position', screenSize);  

end

function menuObjectsStructure = createMenuObjects(parentFigureObject)
    %Create Menu Objects
    menuObjectsStructure.fileMenu = uimenu('Parent', parentFigureObject,...
        'Label', 'File');
    %Load Frame Menu
    menuObjectsStructure.loadFrame = uimenu('Parent', menuObjectsStructure.fileMenu,...
        'Label', 'Open Frame',...
        'Acc', 'O',...
        'Callback', '');
    %Quit Menu
    menuObjectsStructure.quitMenu = uimenu('Parent', menuObjectsStructure.fileMenu,...
        'Label', 'Quit',...        
        'Callback', '');
end
